spring:
  application:
    name:chat-hub-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://58.87.96.86:3306/chat-hub
    username: root
    password: Ccjy88007886
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  # session
  session:
    timeout: 86400
    store-type: redis

# MyBatis-Plus Config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# Port
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

# 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cjy.chathubbackend.controller

